name: Firebase App Distribution

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to main branch

jobs:
  build-and-distribute:
    name: Build and Distribute to Firebase
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js for the frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Replace with the version you need

      # Install dependencies for the FE
      - name: Install Dependencies
        working-directory: ./nodejs
        run: npm install

      # # Build the FE app
      # - name: Build Frontend
      #   working-directory: ./src
      #   run: npm run build

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Authenticate with Firebase using Service Account Key
      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > $HOME/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json

      # Set the Firebase project explicitly (use the project ID directly)
      - name: Set Firebase Project
        run: firebase use --add <cloud-lab-task-1-2c614> --alias default

      # Deploy to Firebase Hosting and Firebase App Distribution
      - name: Deploy to Firebase Hosting and App Distribution
        working-directory: ./src
        run: firebase deploy --only hosting,appdistribution
